parameters:
#    william_ecommerce.example.class: William\EcommerceBundle\Example

services:
#    william_ecommerce.example:
#        class: %william_ecommerce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
